nodeLinker: node-modules
nmHoistingLimits: workspaces

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "@commitlint/cli@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "commitlint@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "@react-native/eslint-config@*":
    peerDependencies:
      "typescript": "*"
  "eslint-plugin-jest@*":
    peerDependencies:
      "typescript": "*"
  "babel-plugin-transform-flow-enums@*":
    peerDependencies:
      "@babel/core": "*"
  "babel-preset-expo@*":
    peerDependencies:
      "@babel/core": "*"
  "expo-linking@*":
    peerDependencies:
      "expo": "*"
  "expo@*":
    peerDependencies:
      "@babel/core": "*"
  "react-native@*":
    peerDependencies:
      "@babel/core": "*"
