export {
  completeEmailAuth,
  configure,
  getSupportedNetworks,
  getSession,
  getTokenBalances,
  getWalletAddress,
  sendTransaction,
  signMessage,
  signOut,
  startEmailAuth,
  verifyMessageSignature,
} from './client';
export type {
  GetTokenBalancesParams,
  OmsClientConfig,
  OmsClientEnvironment,
  OmsSendTransactionResult,
  OmsClientSessionLoginType,
  OmsClientSessionState,
  OmsNetwork,
  OmsTokenBalance,
  OmsTokenBalancesPage,
  OmsTokenBalancesResult,
  OmsTransactionStatus,
  OmsWallet,
  SendTransactionParams,
  VerifyMessageSignatureParams,
} from './types';
