import type { OmsNetwork } from './types';

export const supportedNetworks: OmsNetwork[] = [
  {
    chainId: '1',
    name: 'mainnet',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://etherscan.io',
    displayName: 'Ethereum',
  },
  {
    chainId: '11155111',
    name: 'sepolia',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://sepolia.etherscan.io',
    displayName: 'Sepolia',
  },
  {
    chainId: '137',
    name: 'polygon',
    nativeTokenSymbol: 'POL',
    explorerUrl: 'https://polygonscan.com',
    displayName: 'Polygon',
  },
  {
    chainId: '80002',
    name: 'amoy',
    nativeTokenSymbol: 'POL',
    explorerUrl: 'https://amoy.polygonscan.com',
    displayName: 'Polygon Amoy',
  },
  {
    chainId: '42161',
    name: 'arbitrum',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://arbiscan.io',
    displayName: 'Arbitrum',
  },
  {
    chainId: '421614',
    name: 'arbitrum-sepolia',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://sepolia.arbiscan.io',
    displayName: 'Arbitrum Sepolia',
  },
  {
    chainId: '10',
    name: 'optimism',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://optimistic.etherscan.io',
    displayName: 'Optimism',
  },
  {
    chainId: '11155420',
    name: 'optimism-sepolia',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://sepolia-optimism.etherscan.io',
    displayName: 'Optimism Sepolia',
  },
  {
    chainId: '8453',
    name: 'base',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://basescan.org',
    displayName: 'Base',
  },
  {
    chainId: '84532',
    name: 'base-sepolia',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://sepolia.basescan.org',
    displayName: 'Base Sepolia',
  },
  {
    chainId: '56',
    name: 'bsc',
    nativeTokenSymbol: 'BNB',
    explorerUrl: 'https://bscscan.com',
    displayName: 'BSC',
  },
  {
    chainId: '97',
    name: 'bsc-testnet',
    nativeTokenSymbol: 'BNB',
    explorerUrl: 'https://testnet.bscscan.com',
    displayName: 'BSC Testnet',
  },
  {
    chainId: '42170',
    name: 'arbitrum-nova',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://nova.arbiscan.io',
    displayName: 'Arbitrum Nova',
  },
  {
    chainId: '43114',
    name: 'avalanche',
    nativeTokenSymbol: 'AVAX',
    explorerUrl: 'https://subnets.avax.network/c-chain',
    displayName: 'Avalanche',
  },
  {
    chainId: '43113',
    name: 'avalanche-testnet',
    nativeTokenSymbol: 'AVAX',
    explorerUrl: 'https://subnets-test.avax.network/c-chain',
    displayName: 'Avalanche Testnet',
  },
  {
    chainId: '747474',
    name: 'katana',
    nativeTokenSymbol: 'ETH',
    explorerUrl: 'https://katanascan.com',
    displayName: 'Katana',
  },
];
