name: Quick Checks

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Install Expo example dependencies
        run: npm --prefix examples/expo-example ci

      - name: Typecheck files
        run: yarn typecheck

      - name: Typecheck Expo example
        run: npm --prefix examples/expo-example run typecheck
